services:
  mongodb:
    image: mongo:latest
    container_name: ms_notify_mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ms_notify
    volumes:
      - mongo_data:/data/db
#    networks:
#      - matheus-network

#  ms-notify:
#    build:
#      dockerfile: Dockerfile
#    container_name: ms-notify
#    restart: always
#    environment:
#      MONGODB_URI: mongodb://mongodb:27017/ms_notify
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    depends_on:
#      - mongodb
#    networks:
#      - matheus-network
#
#networks:
#  matheus-network:
#    driver: bridge

volumes:
  mongo_data:
