spring:
  application:
    name: ms-notify

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

  data:
    mongodb:
      uri: mongodb://localhost:27017/ms_notify

server:
  port: 8081
