services:
  mysql:
    image: 'mysql:8.0.29'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: docker
      MYSQL_PASSWORD: admindocker@123
      MYSQL_DATABASE: ms_usuario
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
#    networks:
#      - matheus-network

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
#    networks:
#      - matheus-network

#  ms-usuario:
#    build:
#      dockerfile: Dockerfile
#    container_name: ms-usuario
#    restart: always
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ms_usuario?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
#      SPRING_DATASOURCE_USERNAME: docker
#      SPRING_DATASOURCE_PASSWORD: admindocker@123
#      RABBITMQ_HOST: rabbitmq
#      RABBITMQ_PORT: 5672
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#    depends_on:
#      - mysql
#      - rabbitmq
#    networks:
#      - matheus-network
#
#networks:
#  matheus-network:
#    driver: bridge


volumes:
  mysql_data:
  rabbitmq_data: